players:
  - yuto.komai
allocation:
  市民: 1
  予言者(占い師): 0
  霊媒師: 0
  騎士(ボディーガード): 0
  独裁者: 0
  パン屋: 0
  人狼: 0
  人狼の子供: 0
  裏切り者(狂人): 0
  妖狐: 0
  騎士団: 0
  共有者(双子): 0
  罠師: 0
  奇術師: 0
  裏切りの共有者: 0
  内通者: 0
  スパイ: 0
  アンドロイド: 0
role:
  市民:
    概要: 市民サイドの基本的な職業です。
    特殊能力: なし
    勝利条件: 人狼および第三者陣営を全て追放すること
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: あなたの1票が大きく展開を左右します
  予言者(占い師):
    概要: 市民サイドの強力なエース職業です。
    特殊能力: 毎ターン夜に1名を指名し「市民サイド」か「人狼サイド」かを占うことが出来ます。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: あなたの占い結果に村の平和がかかっています！
  霊媒師:
    概要: 市民サイドの隠れたエース職業です。
    特殊能力: 村から追放されたプレイヤーが「市民サイド」か「人狼サイド」かを知ることが出来ます。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 予言者(占い師)の発言をサポートできるといいでしょう
  騎士(ボディーガード):
    概要: 市民サイドの強力な職業です
    特殊能力: 毎ターン夜に1名を指名し、人狼の襲撃を防ぐことが出来ます。ただし連続して同じ人は選べません。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 連続ガードあり/なしはローカルルールですので確認しましょう
  騎士団:
    概要: 騎士の上位互換、最強役職です
    特殊能力: お互いが騎士団であることを知った状態でプレイ開始できます。通常の騎士の能力に加え、連続ガード可能、自身のガードも可能。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 何をやっても強い。あなたがいるだけで、人狼からしたらやりづらさMAXの村になります
  独裁者:
    概要: 市民サイドの一発屋です
    特殊能力: 正体を明かせば、1度だけ議論を強制終了し、その日追放する人を自分で決めることが出来ます。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 自分が追放されそうになった際のカウンターにつかうと嫌なヤツになれます
  共有者(双子):
    概要: 市民サイドの役職です
    特殊能力: お互いが共有者であることを知った状態でプレイ開始できます。それ以外は特に能力なし。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 地味だよね。でも硬直しがちな序盤から仕掛けていける役職です
  パン屋:
    概要: 市民サイドの毎日まじめに働くパン屋です。
    特殊能力: 生存している場合は、毎朝パンの香りが漂うナレーションが入ります。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: ゲーム追放時の翌朝にめちゃくちゃ悲しまれます。こんな悲しまれる職業他にありません。
  罠師:
    概要: 市民サイドの超強力なカウンター職業です。
    特殊能力: 毎ターン夜に1名を指名し、そのプレイヤーを人狼が襲撃すると人狼が1体死亡します。人狼が複数生存している場合、犠牲になる人狼はランダムで選ばれます。連続で同じ人に罠を仕掛けることはできません。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: ちょっと強すぎるので、予言者とかボディーガード抜きでやる場合などにでも。
  奇術師:
    概要: 市民サイドの強力なカウンター職業です。
    特殊能力: 1度だけ人狼の襲撃先を変更することができる。襲撃先に選ばれると人狼であっても、騎士に守られていても息絶える。
    勝利条件: 市民と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 初日に人狼を吊って、夜に奇術師の能力で人狼を襲撃する最速終了パターンを実現できると気持ちぃぃぃ
  人狼:
    概要: このゲームの最重要役職、人狼です。
    特殊能力: 仲間の人狼が誰かわかります。初日を除く夜のターンに人狼以外のプレイヤーを1人襲撃することができます。
    勝利条件: 人狼と市民の人数が一致したタイミングで人狼の勝利となります。
    予言者(占い師)の結果: 黒
    霊媒師の結果: 黒
    一言: あなたは嘘をつき続けことができるか？
  人狼の子供:
    概要: 人狼サイドの強力なカウンター職業です。
    特殊能力: 昼に人狼の子どもが追放されると、その夜の人狼の襲撃が2回になる。
    勝利条件: 人狼と同じ
    予言者(占い師)の結果: 黒
    霊媒師の結果: 黒
    一言: 死んでもオイシイので、あまり難しく考えずに好き勝手やっていい役職
  裏切り者(狂人):
    概要: 人狼サイドの職業です。狼を生き残らせて勝利に導くことが役割です
    特殊能力: 人狼サイドですが、占い結果が市民として出ます。人狼と裏切り者はお互い認知できません。
    勝利条件: 人狼と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: やりたい放題やりましょう。だってあなたは狂人なのですから
  裏切りの共有者:
    概要: 人狼サイドの職業です。
    特殊能力: 人狼サイドですが、占い結果が市民として出ます。互いに裏切りの共有者であることを知っている裏切り者。
    勝利条件: 人狼と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 数の暴力によってパワープレイを楽しむことができます。せっかくだからかき回そうぜ。
  内通者:
    概要: 裏切り者の上位互換です。
    特殊能力: 人狼サイドですが、占い結果が市民として出ます。人狼と裏切り者は、お互い認知することができます。
    勝利条件: 人狼と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: ここまで来ると、人狼としてカウントしない以外は、最早人狼。
  スパイ:
    概要: 人狼サイドの強力な職業です。
    特殊能力: 毎ターン夜に市民サイドの誰か1人の能力を使えなくする。妨害は1役職につき1回まで。
    勝利条件: 人狼と同じ
    予言者(占い師)の結果: 白
    霊媒師の結果: 白
    一言: 自身の能力もオイシイですが「今晩、能力が使えませんでした」というウソだらけの議論を展開できるのが胸アツ
  妖狐:
    概要: 市民にも人狼にも属さない第三者陣営
    特殊能力: 人狼の襲撃では死亡しないが、占われると死亡する。
    勝利条件: 市民サイドor人狼サイド勝利時に自分が生き残っていることで、1人勝ちになる
    予言者(占い師)の結果: 白(ただし翌朝死亡)
    霊媒師の結果: 白
    一言: 潜伏しまくって最終日を「人狼・市民・市民・妖狐」の4人で迎えてカミングアウトすると、市民を萎えさせることができる。
  アンドロイド:
    概要: 上級者向けの第三勢力です。
    特殊能力: ゲーム開始時点に1人を選んで能力をコピーできる。
    勝利条件: 自身とコピー相手が生存した状態で、コピーした相手の勝利条件を満たすと1人勝ち。コピーした相手が死亡すると一緒に死亡します。人狼をコピーした場合は、人狼と一緒には起きず、アンドロイドのみで襲撃を行います。
    予言者(占い師)の結果: 白or黒
    霊媒師の結果: 白or黒
    一言: ルール上矛盾が出てきそうな、ゲームマスターも大混乱職業です
